AUTH_PHONE, AUTH_CODE, AUTH_PASSWORD = range(3)
(
    ADD_CHAT_NAME,
    ADD_CHAT_SOURCE,
    ADD_CHAT_DEST,
    ADD_CHAT_TIME,
    ADD_CHAT_HOURS,
    ADD_CHAT_PROMPT,
) = range(3, 9)
EDIT_PROMPT, EDIT_TIME, EDIT_HOURS, EDIT_SOURCE_DEST = range(9, 13)
SEARCH_QUERY = 13
