AUTH_LABEL, AUTH_PHONE, AUTH_CODE, AUTH_PASSWORD = range(4)
(
    ADD_CHAT_NAME,
    ADD_CHAT_SESSION,
    ADD_CHAT_SOURCE,
    ADD_CHAT_DEST,
    ADD_CHAT_TIME,
    ADD_CHAT_HOURS,
    ADD_CHAT_PROMPT,
) = range(4, 11)
EDIT_PROMPT, EDIT_TIME, EDIT_HOURS, EDIT_SOURCE_DEST, EDIT_KEYWORDS = range(11, 16)
EDIT_SESSION_LABEL = 16
SEARCH_QUERY = 17
